version: '3'
services:
  frontend:
    build: 
      context: frontend
    command: npm start
    ports:
      - 3000:3000
  backend:
    build: 
      context: backend
    command: npm start
    ports:
      - 5000:5000
  
